import ROOT
import yaml


ROOT.EnableImplicitMT()
ROOT.gROOT.SetBatch(True)

with open("configurations.yaml", "r") as stream:
  confFile = yaml.safe_load(stream)
  conf = confFile["template_preparation"]
  confAn = confFile["analysis"]

dataDfMB = ROOT.RDataFrame("tree", "snapshots/data_mb.root")
dataDf = ROOT.RDataFrame("tree", "snapshots/data.root")
primaryDf = ROOT.RDataFrame("tree", "snapshots/primary.root")
charmDf = ROOT.RDataFrame("tree", "snapshots/charm.root")
beautyDf = ROOT.RDataFrame("tree", "snapshots/beauty.root")

outFile = ROOT.TFile(conf['outputFilename'], "recreate")
purityDir = outFile.mkdir("purity")
mcDir = purityDir.mkdir("mc")
dataDir = purityDir.mkdir("data")

massMB = dataDfMB.Histo2D(("hMassMB", ";#it{p}_{T} (GeV/#it{c});#it{m} (GeV/#it{c}^{2})", confAn['nPtBins'], confAn['minPt'], confAn['maxPt'], 70, 1.64, 1.71), "fCascPt", "fMassOmega")
massMC = primaryDf.Histo2D(("hMassMC", ";#it{p}_{T} (GeV/#it{c});#it{m} (GeV/#it{c}^{2})", confAn['nPtBins'], confAn['minPt'], confAn['maxPt'], 70, 1.64, 1.71), "fCascPt", "fMassOmega")

wsPurity = ROOT.RooWorkspace("wsPurity")
wsPurity.factory("RooCrystalBall::signal(mass[1.64, 1.71], mu[1.68, 1.64, 1.71], sigma[0.01, 0.001, 0.1], alphaL[1.5, 0.1, 10], nL[1.5, 0.1, 10], alphaR[1.5, 0.1, 10], nR[1.5, 0.1, 10])")
wsPurity.factory("RooExponential::background(mass, lambda[-1, -40, 0])")
wsPurity.factory("SUM::model(fraction[0.5, 0, 1]*signal, background)")

hPurity = ROOT.TH1D("hPurity", ";#it{p}_{T} (GeV/#it{c});Fraction of signal", confAn['nPtBins'], confAn['minPt'], confAn['maxPt'])
hMean = ROOT.TH1D("hMean", ";#it{p}_{T} (GeV/#it{c});#mu of the signal (GeV/#it{c}^{2})", confAn['nPtBins'], confAn['minPt'], confAn['maxPt'])
hSigma = ROOT.TH1D("hSigma", ";#it{p}_{T} (GeV/#it{c});#sigma of the signal (GeV/#it{c}^{2})", confAn['nPtBins'], confAn['minPt'], confAn['maxPt'])
for i in range(confAn['nPtBins']):
  datasetMC = ROOT.RooDataHist(f"datasetMC_{i}", f"datasetMC_{i}", ROOT.RooArgList(wsPurity.var("mass")), massMC.ProjectionY(f"hMassMC_{i}", i+1, i+1))
  wsPurity.pdf("signal").fitTo(datasetMC)
  plotMC = wsPurity.var("mass").frame()
  datasetMC.plotOn(plotMC)
  wsPurity.pdf("signal").plotOn(plotMC)
  mcDir.cd()
  plotMC.Write(f"frameMC_{i}")

  wsPurity.var("alphaR").setConstant(True)
  wsPurity.var("alphaL").setConstant(True)
  wsPurity.var("nR").setConstant(True)
  wsPurity.var("nL").setConstant(True)

  datasetMB = ROOT.RooDataHist(f"datasetMB_{i}", f"datasetMB_{i}", ROOT.RooArgList(wsPurity.var("mass")), massMB.ProjectionY(f"hMassMB_{i}", i+1, i+1))
  wsPurity.pdf("model").fitTo(datasetMB)
  plotMB = wsPurity.var("mass").frame()
  datasetMB.plotOn(plotMB)
  wsPurity.pdf("model").plotOn(plotMB)
  wsPurity.pdf("model").paramOn(plotMB)

  wsPurity.var("alphaR").setConstant(False)
  wsPurity.var("alphaL").setConstant(False)
  wsPurity.var("nR").setConstant(False)
  wsPurity.var("nL").setConstant(False)

  mean = wsPurity.var("mu").getVal()
  sigma = wsPurity.var("sigma").getVal()
  wsPurity.var("mass").setRange(f"sigRange{i}", mean - 2 * sigma, mean + 2 * sigma)
  integralSignal = wsPurity.pdf("signal").createIntegral(ROOT.RooArgSet(wsPurity.var("mass")), ROOT.RooFit.NormSet(ROOT.RooArgSet(wsPurity.var("mass"))), ROOT.RooFit.Range(f"sigRange{i}"))
  integralModel = wsPurity.pdf("model").createIntegral(ROOT.RooArgSet(wsPurity.var("mass")), ROOT.RooFit.NormSet(ROOT.RooArgSet(wsPurity.var("mass"))), ROOT.RooFit.Range(f"sigRange{i}"))
  fractionSignal = integralSignal.getVal() * wsPurity.var("fraction").getVal() / integralModel.getVal()
  hMean.SetBinContent(i+1, mean)
  hMean.SetBinError(i+1, wsPurity.var("mu").getError())
  hSigma.SetBinContent(i+1, sigma)
  hSigma.SetBinError(i+1, wsPurity.var("sigma").getError())
  hPurity.SetBinContent(i+1, fractionSignal)

  dataDir.cd()
  plotMB.Write(f"frameMB_{i}")

purityDir.cd()
hMean.Fit("pol0")
averageMass = hMean.GetFunction("pol0").GetParameter(0)
hSigma.Fit("pol4")
sigPars = [hSigma.GetFunction("pol4").GetParameter(i) for i in range(5)]
sigmaFilter = f"({sigPars[0]} + {sigPars[1]} * fCascPt + {sigPars[2]} * fCascPt * fCascPt + {sigPars[3]} * fCascPt * fCascPt * fCascPt + {sigPars[4]} * fCascPt * fCascPt * fCascPt * fCascPt)"
hMean.Write()
hSigma.Write()
hPurity.Write()

signalDataDf = dataDf.Filter(f"fMassOmega > {averageMass} - 2 * {sigmaFilter} && fMassOmega < {averageMass} + 2 * {sigmaFilter}")
backgroundDataDf = dataDf.Filter(f"fMassOmega < {averageMass} - 5 * {sigmaFilter} || fMassOmega > {averageMass} + 5 * {sigmaFilter}")
hMassSignal = signalDataDf.Histo2D(("hMassSignal", ";#it{p}_{T} (GeV/#it{c});#it{m} (GeV/#it{c}^{2})", conf['nPtBins'], conf['minPt'], conf['maxPt'], 70, 1.64, 1.71), "fCascPt", "fMassOmega")
hMassBackground = backgroundDataDf.Histo2D(("hMassBackground", ";#it{p}_{T} (GeV/#it{c});#it{m} (GeV/#it{c}^{2})", conf['nPtBins'], conf['minPt'], conf['maxPt'], 70, 1.64, 1.71), "fCascPt", "fMassOmega")
purityDir.cd()
hMassSignal.Write()
hMassBackground.Write()

hDCAxyData = signalDataDf.Histo2D(("hDCAxyData", ";#it{p}_{T} (GeV/#it{c});DCA_{xy} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'], conf['nBinsDCAxy'], -conf['maxAbsDCAxy'], conf['maxAbsDCAxy']), "fCascPt", "fCascDCAxy")
hDCAxyBackground = backgroundDataDf.Histo2D(("hDCAxyBackground", ";#it{p}_{T} (GeV/#it{c});DCA_{xy} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'], conf['nBinsDCAxy'], -conf['maxAbsDCAxy'], conf['maxAbsDCAxy']), "fCascPt", "fCascDCAxy")
hDCAxyPrimary = primaryDf.Histo2D(("hDCAxyPrimary", ";#it{p}_{T} (GeV/#it{c});DCA_{xy} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'], conf['nBinsDCAxy'], -conf['maxAbsDCAxy'], conf['maxAbsDCAxy']), "fCascPt", "fCascDCAxy")
hDCAxyCharm = charmDf.Histo2D(("hDCAxyCharm", ";#it{p}_{T} (GeV/#it{c});DCA_{xy} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'], conf['nBinsDCAxy'], -conf['maxAbsDCAxy'], conf['maxAbsDCAxy']), "fCascPt", "fCascDCAxy")
hDCAxyBeauty = beautyDf.Histo2D(("hDCAxyBeauty", ";#it{p}_{T} (GeV/#it{c});DCA_{xy} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'], conf['nBinsDCAxy'], -conf['maxAbsDCAxy'], conf['maxAbsDCAxy']), "fCascPt", "fCascDCAxy")

primaryTplDir = outFile.mkdir("primaryTpl")
primaryTplDir.cd()
hDCAxyPrimary.Write()
charmTplDir = outFile.mkdir("charmTpl")
charmTplDir.cd()
hDCAxyCharm.Write()
beautyTplDir = outFile.mkdir("beautyTpl")
beautyTplDir.cd()
hDCAxyBeauty.Write()
backgroundTplDir = outFile.mkdir("backgroundTpl")
backgroundTplDir.cd()
hDCAxyBackground.Write()

hSigmaPrimary = ROOT.TH1D("hSigmaPrimary", ";#it{p}_{T} (GeV/#it{c});#sigma_{DCA_{xy}} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'])
hSigmaCharm = ROOT.TH1D("hSigmaCharm", ";#it{p}_{T} (GeV/#it{c});#sigma_{DCA_{xy}} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'])
hSigmaBeauty = ROOT.TH1D("hSigmaBeauty", ";#it{p}_{T} (GeV/#it{c});#sigma_{DCA_{xy}} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'])
hSigmaBkg = ROOT.TH1D("hSigmaBkg", ";#it{p}_{T} (GeV/#it{c});#sigma_{DCA_{xy}} (cm)", conf['nPtBins'], conf['minPt'], conf['maxPt'])

hAlphaRPrimary = ROOT.TH1D("hAlphaRPrimary", ";#it{p}_{T} (GeV/#it{c});#alpha_{R}", conf['nPtBins'], conf['minPt'], conf['maxPt'])
hAlphaRCharm = ROOT.TH1D("hAlphaRCharm", ";#it{p}_{T} (GeV/#it{c});#alpha_{R}", conf['nPtBins'], conf['minPt'], conf['maxPt'])
hAlphaRBeauty = ROOT.TH1D("hAlphaRBeauty", ";#it{p}_{T} (GeV/#it{c});#alpha_{R}", conf['nPtBins'], conf['minPt'], conf['maxPt'])
hAlphaRBkg = ROOT.TH1D("hAlphaRBkg", ";#it{p}_{T} (GeV/#it{c});#alpha_{R}", conf['nPtBins'], conf['minPt'], conf['maxPt'])

dcaxy = ROOT.RooRealVar("dcaxy", "DCA_{xy}", 0., -conf['maxAbsDCAxy'], conf['maxAbsDCAxy'], "cm")
muDCAxy = ROOT.RooRealVar("muDCAxy", "#mu_{DCA_{xy}}", 0., -conf['maxAbsDCAxy'], conf['maxAbsDCAxy'], "cm")
sigmaDCAxy = ROOT.RooRealVar("sigmaDCAxy", "#sigma_{DCA_{xy}}", 1.e-3, 1.e-4, 1.e-2, "cm")
alphaR = ROOT.RooRealVar("alphaR", "#alpha_{R}", 1.5, 0.01, 10.)
alphaL = ROOT.RooFormulaVar("alphaL", "#alpha_{L}", "-@0", ROOT.RooArgList(alphaR))
gausExpMCxy = ROOT.RooGausDExp("gausExpMCxy", "GausDExp", dcaxy, muDCAxy, sigmaDCAxy, alphaL, alphaR)

def get_and_store_templates(dataset, sigmaHist, alphaRHist, tplDir, i, name):
    gausExpMCxy.fitTo(dataset)
    plot = dcaxy.frame()
    plot.SetName(f"frameDCAxy{name}_{i}")
    dataset.plotOn(plot, ROOT.RooFit.MarkerSize(0.5), ROOT.RooFit.Name("data"))
    gausExpMCxy.plotOn(plot, ROOT.RooFit.Name("model"))
    gausExpMCxy.paramOn(plot, ROOT.RooFit.Label(f'#chi^{{2}}/NDF = {plot.chiSquare("model", "data")}'))
    sigmaHist.SetBinContent(i+1, sigmaDCAxy.getVal())
    sigmaHist.SetBinError(i+1, sigmaDCAxy.getError())
    alphaRHist.SetBinContent(i+1, alphaR.getVal())
    alphaRHist.SetBinError(i+1, alphaR.getError())
    tplDir.cd()
    plot.Write()

hKSprob = ROOT.TH1D("hKSprob", ";#it{p}_{T} (GeV/#it{c});KS probability", conf['nPtBins'], conf['minPt'], conf['maxPt'])
for i in range(conf['nPtBins']):
  projPrimary = hDCAxyPrimary.ProjectionY(f"hDCAxyPrimary_{i}", i+1, i+1)
  projCharm = hDCAxyCharm.ProjectionY(f"hDCAxyCharm_{i}", i+1, i+1)
  hKSprob.SetBinContent(i+1, projPrimary.KolmogorovTest(projCharm))

  datasetDCAxyBackground = ROOT.RooDataHist(f"datasetDCAxyBackground_{i}", f"datasetDCAxyBackground_{i}", ROOT.RooArgList(dcaxy), hDCAxyBackground.ProjectionY(f"hDCAxyBackground_{i}", i+1, i+1))
  datasetDCAxyPrimary = ROOT.RooDataHist(f"datasetDCAxyPrimary_{i}", f"datasetDCAxyPrimary_{i}", ROOT.RooArgList(dcaxy), projPrimary)
  datasetDCAxyCharm = ROOT.RooDataHist(f"datasetDCAxyCharm_{i}", f"datasetDCAxyCharm_{i}", ROOT.RooArgList(dcaxy), projCharm)
  datasetDCAxyBeauty = ROOT.RooDataHist(f"datasetDCAxyBeauty_{i}", f"datasetDCAxyBeauty_{i}", ROOT.RooArgList(dcaxy), hDCAxyBeauty.ProjectionY(f"hDCAxyBeauty_{i}", i+1, i+1))

  alphaR.setRange(0.8, 3)
  alphaR.setVal(1.)
  sigmaDCAxy.setRange(1.e-4, 1.e-2)
  get_and_store_templates(datasetDCAxyPrimary, hSigmaPrimary, hAlphaRPrimary, primaryTplDir, i, "Primary")
  get_and_store_templates(datasetDCAxyCharm, hSigmaCharm, hAlphaRCharm, charmTplDir, i, "Charm")
  get_and_store_templates(datasetDCAxyBackground, hSigmaBkg, hAlphaRBkg, backgroundTplDir, i, "Background")
  sigmaDCAxy.setRange(sigmaDCAxy.getVal() *0.5, sigmaDCAxy.getVal() *1.5)
  alphaR.setRange(0., 2)
  alphaR.setVal(0.3)
  muDCAxy.setConstant(True)
  get_and_store_templates(datasetDCAxyBeauty, hSigmaBeauty, hAlphaRBeauty, beautyTplDir, i, "Beauty")
  muDCAxy.setConstant(False)

outFile.mkdir("template_shapes").cd()
hKSprob.Write()
hSigmaPrimary.Fit("expo")
hSigmaPrimary.Write()
hSigmaCharm.Fit("expo")
hSigmaCharm.Write()
hSigmaBeauty.Fit("expo")
hSigmaBeauty.Write()
hSigmaBkg.Fit("expo")
hSigmaBkg.Write()
hAlphaRPrimary.Fit("expo")
hAlphaRPrimary.Write()
hAlphaRCharm.Fit("expo")
hAlphaRCharm.Write()
hAlphaRBeauty.Fit("expo")
hAlphaRBeauty.Write()
hAlphaRBkg.Fit("expo")
hAlphaRBkg.Write()
